name: learn_bridge
description: "An e-learning app for students and admins."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  # Go Router
  go_router: ^14.0.0
  # Core Firebase configuration package
  firebase_core: ^3.2.0
  # Firebase Authentication client
  firebase_auth: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Asset pipeline initialization for your onboarding and splash visuals
  assets:
    - assets/images/
